erDiagram
    CLIENTS {
        INT id PK "C.id"
        VARCHAR lib "Client Name"
        VARCHAR number "Phone Number"
    }

    EMPLOYEES {
        INT id PK "E.id"
        VARCHAR lib "Employee Name"
    }

    SERVICES {
        INT id PK "S.id"
        VARCHAR lib "Service Name"
        INT time_value "Base Duration [15, 20, 25, 30] mins"
    }

    EMPLOYEE_X_SERVICES {
        INT id PK "Appointment ID"
        INT id_E FK "Employee ID"
        INT id_S FK "Service ID"
        INT id_C FK "Client ID"
        BOOLEAN x_2 "0=Single, 1=Double Duration"
        TIME start "HH:mm"
        TIME end "HH:mm"
        DATE date "YYYY/MM/DD"
        VARCHAR status "e.g., 'taken', 'free'"
    }

    ES_NOTIFICATION {
        INT id PK "Notification ID"
        INT id_ES FK "Appointment ID"
        VARCHAR type "booking or cancelled"
    }

    CLIENTS ||--o{ EMPLOYEE_X_SERVICES : "Books"
    EMPLOYEES ||--o{ EMPLOYEE_X_SERVICES : "Provides"
    SERVICES ||--o{ EMPLOYEE_X_SERVICES : "Is For"
    EMPLOYEE_X_SERVICES ||--o{ ES_NOTIFICATION : "Has Notification"
